codecov:
  strict_yaml_branch: master

coverage:
  status:
    project:
      default: false
      tests:
        target: 70%
        paths:
          - "tests/"
        if_not_found: success
      package:
        target: 55%
        paths:
          - "smqtk_image_io/"
    patch:
      default: false
      tests:
        target: 100%
        paths:
          - "tests/"
        if_not_found: success
      package:
        target: 80%
        paths:
          - "smqtk_image_io/"
